### ISSUE TITLE
运行出错 java10

### ISSUE THREAD

**Issue by laogavip** [SummerSec/ShiroAttack2#27]
{Transfer-Encoding=[chunked], null=[HTTP/1.1 200], Connection=[close], Vary=[Access-Control-Request-
Headers, Access-Control-Request-Method, Origin], Set-Cookie=[rememberMe=deleteMe; Path=/; Max-Age=0;
 Expires=Wed, 06-Jul-2022 11:47:49 GMT; SameSite=lax], Date=[Thu, 07 Jul 2022 11:47:49 GMT], Content
-Type=[application/json]}{"msg":"运行时异常:null","code":500}
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
MLog initialization issue: slf4j found no binding or threatened to use its (dangerously silent) NOPL
ogger. We consider the slf4j library not found.
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at com.summersec.attack.deser.frame.Shiro.sendpayload(Shiro.java:33)
        at com.summersec.attack.core.AttackService$1.run(AttackService.java:332)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
7月 07, 2022 7:47:57 下午 com.mchange.v2.log.MLog
信息: MLog clients using java 1.4+ standard logging.

**Comment by Telssh** [comment]
你打的命令是？

**Comment by SummerSec** [comment]
历史遗留问题，最新版本已修复。
