### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by R5MTF** [SummerSec/ShiroAttack2#53]
JAVA version openjdk 17.0.8.1 2023-08-24

cracking key error:
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

Exception in thread "Thread-4" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.summersec.attack.deser.frame.Shiro.sendpayload(Shiro.java:33)
	at com.summersec.attack.core.AttackService$2.run(AttackService.java:371)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)

**Comment by R5MTF** [comment]
fix 😄

 <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
        </dependency>
