### ISSUE TITLE
JDK > 1.8 爆破 shiro key 时出错

### ISSUE THREAD

**Issue by lsr00ter** [SummerSec/ShiroAttack2#63]
点击爆破后只检测 shiro 框架，不继续运行，console 报错。如 JDK 22 运行时错误信息：
```
2024-08-15 14:51:24.065 java[68834:1551241] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
MLog initialization issue: slf4j found no binding or threatened to use its (dangerously silent) NOPLogger. We consider the slf4j library not found.
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at com.summersec.attack.deser.frame.Shiro.sendpayload(Shiro.java:33)
        at com.summersec.attack.core.AttackService$1.run(AttackService.java:335)
        at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 3 more
Aug 15, 2024 2:51:47 PM com.mchange.v2.log.MLog
INFO: MLog clients using java 1.4+ standard logging.
```
查了下应该是 `java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter` 这个问题

**Comment by TheNorth-sec** [comment]
大佬解决了吗

**Comment by ThanatosXingYu** [comment]
同问

**Comment by SummerSec** [comment]
使用jdk8试试

**Comment by SummerSec** [comment]
历史遗留问题，最新版本已修复。
